In [ ]:
import pandas
import numpy

In [3]:
dataset = pandas.read_csv("netflix_titles.csv")
dataset.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [36]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       8807 non-null   object
 6   date_added    8709 non-null   datetime64[ns]
 7   release_year  8807 non-null   int32
 8   rating        8807 non-null   object
 9   duration      8807 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int32(1), object(10)
memory usage: 791.4+ KB

In [35]:
# convert date_added to datetime format
dataset["date_added"] = pandas.to_datetime(dataset["date_added"], errors="coerce")

In [26]:
dataset.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [27]:
dataset.shape

(8807, 12)

In [38]:
dataset.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
# setting missing director, cast, country,  to unknown 
dataset["director"] = dataset["director"].fillna("Unknown")
dataset["cast"] = dataset["cast"].fillna("Unknown")
dataset["country"] = dataset["country"].fillna("Unknown")

# setting date added by forward fill method
dataset["date_added"] = dataset["date_added"].fillna(method="ffill")

# dropping missing values from rating
dataset = dataset.dropna(subset=["rating"])

C:\Users\Meet\AppData\Local\Temp\ipykernel_30404\1349205310.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset["date_added"] = dataset["date_added"].fillna(method="ffill")

In [40]:
# duplicate values
dataset.duplicated()
dataset.duplicated().sum()

0

In [45]:
dataset["rating"].unique()
dataset["listed_in"].unique()
# as we can see there are some data which should not be there in the column like 84 min 66 min etc. so we will replace these values with mode of rating values
dataset["rating"] = dataset["rating"].replace(
    ["84 min", "66 min", "74 min", "86 min", "90 min", "NR", "UR","nan"], dataset["rating"].mode()[0]
)

In [47]:
dataset["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', 'TV-Y7-FV'], dtype=object)

In [46]:
dataset["listed_in"].unique()

array(['Documentaries', 'International TV Shows, TV Dramas, TV Mysteries',
       'Crime TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Reality TV',
       'International TV Shows, Romantic TV Shows, TV Comedies',
       'TV Dramas, TV Horror, TV Mysteries', 'Children & Family Movies',
       'Dramas, Independent Movies, International Movies',
       'British TV Shows, Reality TV', 'Comedies, Dramas',
       'Crime TV Shows, Docuseries, International TV Shows',
       'Dramas, International Movies',
       'Children & Family Movies, Comedies',
       'British TV Shows, Crime TV Shows, Docuseries',
       'TV Comedies, TV Dramas', 'Documentaries, International Movies',
       'Crime TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Thrillers',
       'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'International TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies',
       'Comedies, International Movies, Romantic Movies',
       'Docuseries, International TV Shows, Reality TV',
       'Comedies, International Movies, Music & Musicals', 'Comedies',
       'Horror Movies, Sci-Fi & Fantasy', 'TV Comedies',
       'British TV Shows, International TV Shows, TV Comedies',
       'International TV Shows, TV Dramas, TV Thrillers', "Kids' TV",
       'Dramas, International Movies, Thrillers',
       'Action & Adventure, Dramas, International Movies',
       "Kids' TV, TV Comedies", 'Action & Adventure, Dramas',
       "Kids' TV, TV Sci-Fi & Fantasy",
       'Action & Adventure, Classic Movies, Dramas',
       'Dramas, Horror Movies, Thrillers',
       'Action & Adventure, Horror Movies, Thrillers',
       'Action & Adventure', 'Dramas, Thrillers',
       'International TV Shows, TV Dramas',
       'International TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, Anime Features, International Movies',
       'Reality TV', 'Docuseries, International TV Shows',
       'Documentaries, International Movies, Sports Movies',
       'International TV Shows, Reality TV, Romantic TV Shows',
       'British TV Shows, Docuseries, International TV Shows',
       'Anime Series, International TV Shows',
       'Comedies, Dramas, International Movies',
       'Crime TV Shows, TV Comedies, TV Dramas',
       'Action & Adventure, Comedies, Dramas', "Anime Series, Kids' TV",
       'International Movies, Thrillers', "Kids' TV, Korean TV Shows",
       'Documentaries, Sports Movies', 'Sci-Fi & Fantasy, Thrillers',
       'Dramas, International Movies, Romantic Movies',
       'Documentaries, Music & Musicals',
       "Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",
       "British TV Shows, Kids' TV", 'Docuseries, Science & Nature TV',
       'Children & Family Movies, Dramas',
       "Kids' TV, TV Dramas, Teen TV Shows",
       'Crime TV Shows, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, International TV Shows, Spanish-Language TV Shows',
       'Dramas', 'Comedies, Romantic Movies', 'Dramas, Romantic Movies',
       'Comedies, Dramas, Independent Movies',
       'Crime TV Shows, TV Action & Adventure, TV Comedies',
       'Children & Family Movies, Music & Musicals',
       'Action & Adventure, Classic Movies, Cult Movies',
       'International TV Shows, TV Action & Adventure, TV Comedies',
       'Action & Adventure, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies', 'Classic Movies, Comedies, Dramas',
       'Comedies, Cult Movies', 'Comedies, Cult Movies, Music & Musicals',
       'Comedies, Music & Musicals', 'TV Shows',
       'Action & Adventure, International Movies',
       'Anime Series, International TV Shows, Teen TV Shows',
       'Action & Adventure, Children & Family Movies, Cult Movies',
       'Comedies, Dramas, Romantic Movies',
       'Comedies, Cult Movies, Sci-Fi & Fantasy',
       'Classic Movies, Dramas',
       'Action & Adventure, Children & Family Movies, Comedies',
       'Dramas, Faith & Spirituality', 'Documentaries, LGBTQ Movies',
       'Action & Adventure, Classic Movies', 'Docuseries',
       'International TV Shows, TV Comedies',
       'Dramas, Independent Movies',
       'Action & Adventure, Comedies, International Movies',
       'International TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Crime TV Shows, International TV Shows, TV Dramas',
       'Action & Adventure, Horror Movies, International Movies',
       'Comedies, International Movies, Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Music & Musicals',
       'Dramas, International Movies, Music & Musicals',
       'Horror Movies, International Movies', 'Reality TV, Teen TV Shows',
       'Crime TV Shows, TV Dramas, TV Mysteries',
       'International TV Shows, Reality TV',
       'International TV Shows, TV Comedies, TV Dramas',
       'Dramas, Independent Movies, Romantic Movies', 'Horror Movies',
       'Documentaries, LGBTQ Movies, Sports Movies',
       'Horror Movies, International Movies, Thrillers',
       'Action & Adventure, Anime Features',
       'TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy',
       'International TV Shows, Spanish-Language TV Shows, TV Comedies',
       'Children & Family Movies, Comedies, Music & Musicals',
       'Comedies, Independent Movies',
       'Anime Series, International TV Shows, Romantic TV Shows',
       'Classic Movies, Dramas, Independent Movies',
       'International TV Shows, Romantic TV Shows, Spanish-Language TV Shows',
       'International TV Shows, TV Dramas, Teen TV Shows',
       'Stand-Up Comedy',
       'Action & Adventure, Anime Features, Children & Family Movies',
       'International TV Shows, Romantic TV Shows, TV Dramas',
       'International Movies, Music & Musicals',
       'TV Action & Adventure, TV Dramas, TV Mysteries',
       'Horror Movies, Independent Movies, International Movies',
       'Comedies, Cult Movies, International Movies',
       'Classic Movies, Dramas, International Movies', 'Movies',
       'Crime TV Shows, Docuseries',
       'Children & Family Movies, Comedies, Sci-Fi & Fantasy',
       'Anime Series, International TV Shows, TV Thrillers',
       'Action & Adventure, Horror Movies, Sci-Fi & Fantasy',
       'Classic Movies, Comedies, Cult Movies',
       'TV Dramas, Teen TV Shows',
       'Action & Adventure, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Comedies, Dramas',
       'Dramas, Sports Movies',
       'Action & Adventure, Dramas, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies, Cult Movies',
       'Dramas, Independent Movies, Thrillers',
       'TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Thrillers',
       'British TV Shows, International TV Shows, Reality TV',
       'TV Action & Adventure, TV Dramas, Teen TV Shows', 'Anime Series',
       'Crime TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Crime TV Shows, International TV Shows, TV Comedies',
       'Stand-Up Comedy & Talk Shows, TV Comedies',
       'Classic & Cult TV, TV Action & Adventure, TV Dramas',
       'Children & Family Movies, Sports Movies',
       'TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Anime Series, Stand-Up Comedy & Talk Shows', 'TV Dramas',
       'Anime Features, Children & Family Movies, International Movies',
       'Classic & Cult TV, Crime TV Shows, International TV Shows',
       'Crime TV Shows, International TV Shows, Romantic TV Shows',
       'Horror Movies, LGBTQ Movies',
       'Action & Adventure, Dramas, Romantic Movies',
       'Documentaries, International Movies, Music & Musicals',
       'TV Comedies, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Comedies, Sports Movies',
       'Children & Family Movies, Dramas, International Movies',
       'Comedies, Documentaries, International Movies',
       'Romantic TV Shows, TV Dramas',
       'Anime Series, TV Horror, TV Thrillers',
       'International Movies, Romantic Movies',
       'TV Action & Adventure, TV Dramas, TV Sci-Fi & Fantasy',
       "Kids' TV, Korean TV Shows, TV Comedies",
       'British TV Shows, Crime TV Shows, International TV Shows',
       'Crime TV Shows, TV Horror, TV Mysteries',
       'Docuseries, International TV Shows, Science & Nature TV',
       'British TV Shows, International TV Shows, TV Dramas',
       "Kids' TV, TV Action & Adventure, TV Sci-Fi & Fantasy",
       'International Movies, Romantic Movies, Thrillers',
       'Action & Adventure, Cult Movies, International Movies',
       'Action & Adventure, Comedies, Sci-Fi & Fantasy',
       "International TV Shows, Kids' TV, TV Mysteries",
       'Action & Adventure, Thrillers',
       'Dramas, Faith & Spirituality, International Movies',
       'Action & Adventure, Classic Movies, Comedies',
       'Action & Adventure, Comedies, Sports Movies',
       'Action & Adventure, Children & Family Movies, Classic Movies',
       'Action & Adventure, Children & Family Movies, Dramas',
       'Horror Movies, Thrillers', 'Action & Adventure, Romantic Movies',
       'Dramas, Romantic Movies, Sci-Fi & Fantasy',
       'Dramas, Music & Musicals, Romantic Movies',
       'Anime Series, Crime TV Shows, International TV Shows',
       'Reality TV, Romantic TV Shows',
       'International Movies, Music & Musicals, Romantic Movies',
       'Reality TV, TV Action & Adventure, TV Mysteries',
       'Crime TV Shows, TV Dramas',
       'International TV Shows, Reality TV, Spanish-Language TV Shows',
       'Crime TV Shows, TV Dramas, TV Thrillers',
       'British TV Shows, Docuseries',
       'International TV Shows, Korean TV Shows, TV Comedies',
       'Action & Adventure, Anime Features, Classic Movies',
       'TV Action & Adventure, TV Dramas, TV Horror',
       'Crime TV Shows, International TV Shows, TV Thrillers',
       'Anime Series, Crime TV Shows, TV Horror',
       'Anime Features, Documentaries', 'Comedies, Horror Movies',
       'International TV Shows, Spanish-Language TV Shows, Stand-Up Comedy & Talk Shows',
       'Children & Family Movies, Documentaries, International Movies',
       'Romantic TV Shows, TV Comedies, TV Dramas',
       'Dramas, Faith & Spirituality, Romantic Movies',
       'Dramas, Independent Movies, LGBTQ Movies',
       'Comedies, Independent Movies, LGBTQ Movies',
       'Action & Adventure, Cult Movies, Sci-Fi & Fantasy',
       'Cult Movies, Horror Movies',
       'Action & Adventure, Dramas, Sports Movies',
       'Anime Series, Romantic TV Shows, Teen TV Shows',
       'Dramas, International Movies, LGBTQ Movies',
       'Dramas, Romantic Movies, Thrillers',
       'Children & Family Movies, Dramas, Faith & Spirituality',
       'Dramas, International Movies, Sports Movies',
       'Action & Adventure, Horror Movies',
       'Documentaries, International Movies, LGBTQ Movies',
       'Dramas, Independent Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, International Movies',
       'Reality TV, TV Horror, TV Thrillers',
       'TV Action & Adventure, TV Horror, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Sci-Fi & Fantasy',
       'Independent Movies, International Movies, Thrillers',
       'Independent Movies, Thrillers', 'Documentaries, Dramas',
       'Action & Adventure, Sports Movies',
       'Dramas, International Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, Romantic Movies',
       'Horror Movies, Romantic Movies, Sci-Fi & Fantasy',
       'International TV Shows, Stand-Up Comedy & Talk Shows',
       'Action & Adventure, Anime Features, Horror Movies',
       'Cult Movies, Dramas, Music & Musicals', 'TV Dramas, TV Thrillers',
       'Crime TV Shows, International TV Shows, Korean TV Shows',
       'TV Horror, TV Mysteries, TV Thrillers',
       'Comedies, Horror Movies, International Movies',
       'Crime TV Shows, Docuseries, TV Mysteries',
       'Comedies, International Movies, Sports Movies',
       'Classic Movies, Music & Musicals',
       'Reality TV, TV Comedies, TV Horror',
       'Children & Family Movies, Faith & Spirituality, Music & Musicals',
       'International TV Shows, Korean TV Shows, Stand-Up Comedy & Talk Shows',
       'Dramas, Music & Musicals',
       'Docuseries, Science & Nature TV, TV Action & Adventure',
       "British TV Shows, Kids' TV, TV Dramas",
       'International TV Shows, Korean TV Shows, Romantic TV Shows',
       'Horror Movies, Independent Movies',
       "Anime Series, Kids' TV, TV Action & Adventure",
       'Comedies, Dramas, Music & Musicals', 'TV Horror, Teen TV Shows',
       'Comedies, LGBTQ Movies, Thrillers',
       'Docuseries, Reality TV, Science & Nature TV',
       'Crime TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'Romantic TV Shows, Teen TV Shows', 'TV Comedies, Teen TV Shows',
       'Romantic TV Shows, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Sci-Fi & Fantasy',
       'Romantic TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies, LGBTQ Movies',
       'Dramas, Sci-Fi & Fantasy', "Kids' TV, TV Thrillers",
       'TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy',
       'British TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Series, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, TV Comedies',
       'Comedies, Romantic Movies, Sports Movies',
       'TV Action & Adventure, TV Comedies, TV Dramas',
       'Children & Family Movies, Dramas, Sports Movies',
       'Action & Adventure, Dramas, Independent Movies',
       'Spanish-Language TV Shows, TV Dramas', 'Dramas, LGBTQ Movies',
       'TV Horror, TV Mysteries, TV Sci-Fi & Fantasy',
       'Action & Adventure, Dramas, Faith & Spirituality',
       'International TV Shows, TV Mysteries, TV Thrillers',
       'British TV Shows, Classic & Cult TV, International TV Shows',
       'Action & Adventure, Comedies, Independent Movies',
       'Music & Musicals', "British TV Shows, Kids' TV, TV Comedies",
       'Docuseries, Spanish-Language TV Shows',
       'Dramas, Independent Movies, Sports Movies',
       'TV Dramas, TV Mysteries, TV Thrillers',
       'Comedies, LGBTQ Movies, Music & Musicals',
       'International TV Shows, TV Action & Adventure, TV Mysteries',
       "Kids' TV, TV Comedies, Teen TV Shows",
       'International TV Shows, TV Dramas, TV Horror',
       'Comedies, International Movies, Thrillers',
       'Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Mysteries',
       'Children & Family Movies, Documentaries',
       'Music & Musicals, Romantic Movies', 'Romantic Movies',
       'Children & Family Movies, Classic Movies, Comedies',
       'TV Action & Adventure, TV Dramas',
       'Dramas, LGBTQ Movies, Romantic Movies',
       'Children & Family Movies, Comedies, Romantic Movies',
       'Comedies, Sports Movies', 'International Movies',
       'International TV Shows, Romantic TV Shows, TV Mysteries',
       'Stand-Up Comedy & Talk Shows',
       'Action & Adventure, International Movies, Romantic Movies',
       'Reality TV, TV Comedies',
       'Cult Movies, Dramas, International Movies', "Kids' TV, TV Dramas",
       'Crime TV Shows, International TV Shows, TV Mysteries',
       'Action & Adventure, Sci-Fi & Fantasy, Sports Movies',
       'TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers',
       'Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Docuseries, TV Sci-Fi & Fantasy',
       'Anime Features, International Movies',
       "British TV Shows, Classic & Cult TV, Kids' TV",
       'British TV Shows, Reality TV, Romantic TV Shows',
       'Documentaries, Faith & Spirituality, International Movies',
       "Kids' TV, Reality TV, TV Dramas", 'LGBTQ Movies, Thrillers',
       'TV Action & Adventure, TV Mysteries, TV Sci-Fi & Fantasy',
       'Reality TV, Science & Nature TV',
       "Kids' TV, TV Action & Adventure, TV Comedies",
       'International TV Shows, Romantic TV Shows, TV Action & Adventure',
       'Children & Family Movies, Dramas, Independent Movies',
       'Comedies, Music & Musicals, Romantic Movies',
       'International TV Shows, Korean TV Shows, Reality TV',
       'Classic & Cult TV, TV Dramas, TV Sci-Fi & Fantasy',
       'Anime Features, Children & Family Movies',
       'Action & Adventure, International Movies, Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure, TV Dramas',
       'Classic & Cult TV, TV Action & Adventure, TV Horror',
       'International TV Shows, Korean TV Shows, TV Dramas',
       'International TV Shows, TV Action & Adventure, TV Horror',
       'Action & Adventure, Comedies, Romantic Movies',
       'International TV Shows, Korean TV Shows, TV Action & Adventure',
       "Classic & Cult TV, Kids' TV, TV Action & Adventure",
       'Anime Series, International TV Shows, TV Horror',
       'International TV Shows, Korean TV Shows, TV Horror',
       'Children & Family Movies, Comedies, International Movies',
       'International Movies, Sci-Fi & Fantasy',
       'International Movies, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Dramas, Romantic Movies',
       'Anime Series, Romantic TV Shows',
       'Comedies, Dramas, LGBTQ Movies',
       'British TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Science & Nature TV, TV Comedies',
       'International TV Shows, Stand-Up Comedy & Talk Shows, TV Comedies',
       'Children & Family Movies, Dramas, Music & Musicals',
       'Action & Adventure, Independent Movies, International Movies',
       'Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy',
       'Horror Movies, Independent Movies, Sci-Fi & Fantasy',
       'TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows',
       'Anime Features, International Movies, Sci-Fi & Fantasy',
       'Dramas, Independent Movies, Music & Musicals',
       "Kids' TV, TV Comedies, TV Dramas",
       'Children & Family Movies, Documentaries, Sports Movies',
       'Independent Movies, Sci-Fi & Fantasy, Thrillers',
       'Anime Features, Music & Musicals, Sci-Fi & Fantasy',
       'TV Comedies, TV Dramas, TV Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure',
       'Comedies, Faith & Spirituality, Romantic Movies',
       "Kids' TV, TV Action & Adventure",
       'Action & Adventure, Independent Movies',
       'International TV Shows, Reality TV, TV Comedies',
       'Docuseries, Reality TV, Teen TV Shows',
       'Crime TV Shows, International TV Shows, Reality TV',
       'Anime Series, Teen TV Shows',
       'Crime TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Features, Romantic Movies',
       'Horror Movies, Sci-Fi & Fantasy, Thrillers',
       'International TV Shows, TV Comedies, TV Sci-Fi & Fantasy',
       'International TV Shows, Romantic TV Shows',
       'Anime Features, Music & Musicals',
       'Anime Features, International Movies, Romantic Movies',
       'International TV Shows, Romantic TV Shows, Teen TV Shows',
       'Docuseries, Stand-Up Comedy & Talk Shows',
       'Horror Movies, Independent Movies, Thrillers',
       'TV Action & Adventure, TV Comedies, TV Horror',
       'Documentaries, Stand-Up Comedy',
       "Kids' TV, Spanish-Language TV Shows",
       "British TV Shows, Kids' TV, TV Thrillers",
       "Kids' TV, TV Action & Adventure, TV Dramas",
       'Anime Series, Crime TV Shows',
       'Dramas, Sci-Fi & Fantasy, Thrillers',
       'TV Comedies, TV Dramas, TV Horror',
       'Children & Family Movies, Comedies, LGBTQ Movies',
       'International TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Docuseries, TV Dramas',
       'Horror Movies, International Movies, Romantic Movies',
       'Crime TV Shows, Docuseries, Science & Nature TV',
       'International Movies, Music & Musicals, Thrillers',
       "Kids' TV, Spanish-Language TV Shows, Teen TV Shows",

what i did vs (what was supposed to be done !)


1. LOAD and Understand data (correctly done)
2. date(object) to datetime datatype change (correctly done)
3. checked for dupes (none)(correctly done)
4. director, cast, country unknown (correctly done)
5. date imputed (it was not supposed to be done as it does not changes or provides any extra meaning and also it is factually wrong)
6. replaced rating values of minutes and season,nr,ur with mode (instead i have checked unique values of ratings and swap them with the real rows , here data was correct and valid but just misplaced so swapped data from ratings and duration of that threee data )
7. not unified the ur nr values instead i added mode of the ratings which was wrong (i should have just unify nr ur not rated into not rated )